<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="DESKTOP-OEJBSOD" failures="0" tests="1" name="Default test" time="20.369" errors="0" timestamp="2021-01-19T13:44:47 GMT+05:30">
  <testcase classname="DashBoard.DasboardItems" name="@BeforeTest loginNsetup" time="20.322">
    <failure type="java.lang.AssertionError" message="The login failed expected [Dashboard] but found [null]">
      <![CDATA[java.lang.AssertionError: The login failed expected [Dashboard] but found [null]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at DashBoard.DasboardItems.loginNsetup(DasboardItems.java:71)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:617)
at org.testng.TestRunner.beforeRun(TestRunner.java:607)
at org.testng.TestRunner.run(TestRunner.java:578)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @BeforeTest loginNsetup -->
  <testcase classname="DashBoard.DasboardItems" name="searchStudent" time="0.0">
    <skipped/>
  </testcase> <!-- searchStudent -->
  <testcase classname="DashBoard.DasboardItems" name="paginationStudentList" time="0.0">
    <ignored/>
  </testcase> <!-- paginationStudentList -->
  <testcase classname="DashBoard.DasboardItems" name="advancedSearch" time="0.0">
    <ignored/>
  </testcase> <!-- advancedSearch -->
  <testcase classname="DashBoard.DasboardItems" name="logout" time="0.0">
    <ignored/>
  </testcase> <!-- logout -->
  <testcase classname="DashBoard.DasboardItems" name="createstudent" time="0.0">
    <ignored/>
  </testcase> <!-- createstudent -->
</testsuite> <!-- Default test -->
